config/routes.rb
Notebook::Application.routes.draw do
  resources :notes

  get "pages/mockup"

  root "notes#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to notes_url, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
        format.js { render js: 'alert("Cannot be blank");' }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:content)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def mockup
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notebook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.10.3/themes/cupertino/jquery-ui.css">
</head>
<body>
  <div id="container" class="notepad">
    <header>
      <div id="theme_links">
        <%= link_to 'Legal Pad', '#', :id => 'legalpad_link' %>
        |
        <%= link_to "Notepad", '#', :id => 'notepad_link' %>
      </div>
      <h1>
        <%= link_to image_tag('bulb.jpg', :size => '75x100'), root_url %>
        <%= link_to 'Aha! Notebook', root_url %>
      </h1>
    </header>
    <section>
      <%= yield %>
    </section>
  </div>
</body>
</html>

app/views/notes/_embedded_form.html.erb
<%= form_for note, remote: true do |f| %>
  <%= f.text_field :content, placeholder: 'Add a new note' %>
<% end %>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<li id="note_<%= note.id %>" class="note" data-note-id="<%= note.id %>">
  <%= note.content %>
  <div>
    <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_note_path(note), remote: true %>
    <%= link_to '<i class="icon-trash"></i>'.html_safe, note, method: :delete, remote: true %>
  </div>
</li>

app/views/notes/create.js.erb
<% publish_to "/notes/create" do %>
  var note_element = $('<%= escape_javascript(render 'note', :note => @note) %>');
  note_element.css("display", "none");
  $('#new_note').parent().before(note_element);
  note_element.slideDown();
<% end %>

$('#new_note #note_content').val('');

app/views/notes/destroy.js.erb
<% publish_to "/notes/destroy" do %>
  $('#note_<%= @note.id %>').slideUp();
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/edit.js.erb
$('#note_<%= @note.id %>').html('<%= escape_javascript(render 'embedded_form', :note => @note) %>');

app/views/notes/index.html.erb
<div id="trash" style="height: 200px; border: thin red solid;">

</div>

<ul>
  <% @notes.each do |the_note| %>
    <%= render 'note', :note => the_note %>
  <% end %>
  <li>
    <%= render 'embedded_form', :note => Note.new %>
  </li>
</ul>

<%= subscribe_to "/notes/create" %>
<%= subscribe_to "/notes/destroy" %>
<%= subscribe_to "/notes/update" %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/notes/update.js.erb
<% publish_to "/notes/update" do %>
  $('#note_<%= @note.id %>').replaceWith('<%= escape_javascript(render 'note', :note => @note) %>');
<% end %>

app/views/pages/mockup.html.erb
<ul>
  <li>
    Rails Models are Ruby classes intended to represent real-world things.
    <div>
      <a href="#"><i class="icon-edit"></i></a>
      <a href="#"><i class="icon-trash"></i></a>
    </div>
  </li>
  <li>
    Instance variables in controllers hold data for the views.
    <div>
      <a href="#"><i class="icon-edit"></i></a>
      <a href="#"><i class="icon-trash"></i></a>
    </div>
  </li>
  <li>
    Rails is best for database-backed web applications.
    <div>
      <a href="#"><i class="icon-edit"></i></a>
      <a href="#"><i class="icon-trash"></i></a>
    </div>
  </li>
  <li>
    Javascript is pretty cool.
    <div>
      <a href="#"><i class="icon-edit"></i></a>
      <a href="#"><i class="icon-trash"></i></a>
    </div>
  </li>
  <li>
    Pairing accelerates learning.
    <div>
      <a href="#"><i class="icon-edit"></i></a>
      <a href="#"><i class="icon-trash"></i></a>
    </div>
  </li>
  <li>
    <input placeholder="Add a new aha! here" size="50">
  </li>
</ul>